#    __ ___ __  __
#   / //_(_) /_/ /___ __
#  / ,< / / __/ __/ // /
# /_/|_/_/\__/\__/\_, /
#                /___/
#
# Configuration
font_size                   9
remember_window_size        yes
cursor_blink_interval       0.5
cursor_stop_blinking_after  1
scrollback_lines            3000
wheel_scroll_min_lines      1
enable_audio_bell           yes
window_padding_width        5
hide_window_decorations     no
background_opacity          0.98
dynamic_background_opacity  yes
confirm_os_window_close     0
cursor_trail                1

map ctrl+c  copy_to_clipboard
map ctrl+v  paste_from_clipboard

# BEGIN_KITTY_FONTS
font_family      family="Hack"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS


# BEGIN_KITTY_THEME
# Catppuccin-Frappe
include current-theme.conf
# END_KITTY_THEME
#
#
# --- Configuración de la Barra de Pestañas (Nordic Style) ---

# Posición y Estilo
tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted
tab_title_template      "{index}: {title}"

# Colores de la barra (Basados en el tema que acabamos de configurar)
active_tab_foreground   #2E3440
active_tab_background   #88C0D0
active_tab_font_style   bold
inactive_tab_foreground #D8DEE9
inactive_tab_background #3B4252
inactive_tab_font_style normal

# El fondo de la barra donde no hay pestañas
tab_bar_background      #2E3440

# Margen para que no esté pegado al borde (opcional, se ve más limpio)
tab_bar_margin_height   0.0 0.0

